/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DartInput: typeof import('./src/components/input/DartInput.vue')['default']
    NumberButton: typeof import('./src/components/input/NumberButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreInput: typeof import('./src/components/input/ScoreInput.vue')['default']
  }
}
